apiVersion: v1
kind: Service
metadata:
  labels:
    app: balaam-db
    tier: backend
  name: balaam-postgres
  namespace: default
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
  selector:
    app: balaam-db
    tier: backend
  type: ClusterIP
