apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: balaam
spec:
  replicas: 1
  selector:
      matchLabels:
        tier: frontend
        app: balaam
      matchExpressions:
        - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: balaam
        tier: frontend
    spec:
      containers:
      - name: balaam
        imagePullPolicy: Always
        image: penland365/balaam:v0.2.2
        env:
          - name: HTTP_PORT
            value: "6666"
          - name: GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: balaam-secrets
                key: google.api.key
          - name: DARKSKY_API_KEY
            valueFrom:
              secretKeyRef:
                name: balaam-secrets
                key: darksky.api.key
          - name: DATABASE_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: balaam-config
                key: postgres.host
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: balaam-config
                key: postgres.port
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: balaam-config
                key: postgres.db
          - name: DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: balaam-config
                key: postgres.user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: balaam-secrets
                key: postgres.password
          - name: SLACK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: balaam-secrets
                key: slack.client.id
          - name: SLACK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: balaam-secrets
                key: slack.client.secret
          - name: SLACK_REDIRECT_URI
            valueFrom:
              configMapKeyRef:
                name: balaam-config
                key: slack.redirect.uri
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: balaam-secrets
                key: github.client.id
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: balaam-secrets
                key: github.client.secret
        ports:
        - containerPort: 6666
